### ISSUE TITLE
the animation is bugged

### ISSUE THREAD

**Issue by hackforyouoin** [AleRabo/SCP999#3]
hello idk if this happens to other people but in my server i have issue with this. when he does the animation its so broken. and also he is floating and not flat. and the left arm is also bugged how can i fix this?
![image](https://github.com/user-attachments/assets/58b88142-3759-4e80-8e0d-37cb7a42dcf8)
![image](https://github.com/user-attachments/assets/9949411d-a0ba-45bf-a29d-2ee10a48eeea)

**Comment by AleRabo** [comment]
The plugin is discontinued and was never finished, it’s not meant to be open to the public.
I’ll maybe remake it in the future, just maybe.

**Comment by hackforyouoin** [comment]
i did saw this one fixed in a server so i had to ask it. got it

**Comment by AleRabo** [comment]
Maybe i posted a working version in this repository, but it’s probably unefficient and bad, if you want you could check the previous versions
